name: Run Combo Tool
on:
  workflow_dispatch:

jobs:
  execute-tool:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository Files
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Libraries
      run: |
        pip install requests beautifulsoup4

    - name: Run Main Script
      run: |
        python main.py